services:
  db:
    image: postgis/postgis:15-3.3
    container_name: convenience_store_db
    environment:
      POSTGRES_DB: convenience_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - db_dev:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  
  test-db:
    image: postgis/postgis:15-3.3
    container_name: convenience_store_test_db
    environment:
      POSTGRES_DB: convenience_store_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - db_test:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: convenience_store_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_dev:
  db_test: