# Generated by Django 4.2.7 on 2025-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city', 'district_type'], name='stores_dist_city_81b77f_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['is_active', 'district_type'], name='stores_dist_is_acti_55a4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category', 'is_available'], name='stores_inve_categor_ed83ff_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['store', 'is_available'], name='stores_inve_store_i_da32a2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category', 'unit'], name='stores_inve_categor_d1d146_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['store', 'category', 'is_available'], name='stores_inve_store_i_17b3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city', 'district'], name='stores_stor_city_19b562_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_type', 'is_active'], name='stores_stor_store_t_261f92_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['district_obj', 'store_type'], name='stores_stor_distric_4ff339_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'store_type', 'city'], name='stores_stor_is_acti_784a9f_idx'),
        ),
    ]
