# Generated by Django 4.2.7 on 2024-01-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='min_stock_level',
        ),
    ] 