# Generated by Django 4.2.7 on 2024-01-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_inventory_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ] 