# Generated by Django 4.2.7 on 2025-06-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_item_unit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='stores_inve_quantit_d2778a_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='stores_inve_min_sto_b134b2_idx',
        ),
    ]
