# Generated by Django 4.2.7 on 2025-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_change_district_boundary_to_multipolygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('7-eleven', '7-Eleven'), ('satrafoods', 'Satrafoods'), ('familymart', 'FamilyMart'), ('ministop', 'MINISTOP'), ('bach-hoa-xanh', 'Bách hóa XANH'), ('gs25', 'GS25'), ('circle-k', 'Circle K'), ('winmart', 'WinMart'), ('coopxtra', 'Co.opXtra'), ('other', 'Other')], default='other', help_text='Store brand/type', max_length=50),
        ),
    ]
