# Generated by Django 4.2.7 on 2025-08-17 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Name for anonymous reviews', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
